travis:
  secure:
    BINSTAR_TOKEN: wseggtg5iAbERyGtimIVboSUJbFxhQ4WcTNTsS8FraNvn8gtghAeWmS5VSmAR6A0RD+kUWlqhYwgvNkmt5FSfBGNNdKCA/PAYTuP1NOtxLSANcG+ZEY+qq//f131rzUO4kvPzAirGZEMAHMxaIsPp97d7XRQ/pB4WMps2mukZCqp/locje6BsAT/uQl2SzTpv8a+AsqHu0XsI/i3e7t1MJHErRNf+KNIzhRi4X9PSO2xE6ZjaxPe9rWntIHm1RRFMveHTQQbEfoWF7Bp7JyDPCIXbKMyNNTFC5sXMlpXqj7lRjikHdPz8YaMIagpgbkbPhuPbVm6IP+E7CABILhisdzzwWo0w/dHq2MvWItEViNSZPU3nuD+MEUC0La1liNopgLztIUk6rIwQFSPUyrGwzJQxHzz2ABlc7dhD4E8t1HUfzP32AqLEltGhGqP+yFQcQ8QP6b/UW66IcnrwMaJ/Of+BTsHiXo4v5+8Lv3pma8EA1dkzBqXACS2RGBvEKAPjbq0rosqRi8LPbtgVzXisAx2smrL8lFF5YQdUkQAAQb4NL/VrWiLhAeqmPLuBkoVmV7yMTuG347fhuY386YqBbsmyVg4zH2bG5hko5vul1f2M2mwom0kiSVvc8eGIqGzqMD5beNYuqANYfSpamvzld/asHDRVttSLRdcStg45bQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
